language: objective-c
before_install:
 - gem install xcpretty
 - gem install cocoapods
 - pod setup
script:
- xcodebuild -workspace iosdemo.xcworkspace -scheme iosdemo -sdk iphonesimulator test | xcpretty -tc

