language: objective-c
before_install:
 - brew update
 - brew install xctool
 - gem install cocoapods
 - pod setup
script:
- xctool -workspace iosdemo.xcworkspace -scheme iosdemo test -sdk iphonesimulator

